---
- name: Demonstrate Serial
  hosts: centos
  serial: 1
  max_fail_percentage: 200
  tasks:
     - name: download file
       ansible.builtin.get_url:
         url: " {{ file_path }}"
         dest: /home/student
         owner: student
         group: student
     - name: print a statement
       ansible.builtin.debug:
         msg: "WELCOME TO THIS TASK"
          