---
- name: Demonstrate ansible facts
  hosts: centos
  tasks:
    - name: Display hostname
      ansible.builtin.debug:
        var: ansible_facts['nodename']
    - name: Display all faccts
      ansible.builtin.debug:
        var: ansible_facts
- name: Demonstrate custom facts
  hosts: centos
  tasks:
    - name: Display distribution
      ansible.builtin.debug:
        msg: >
          The distribution for {{  inventory_hostname }} is {{ ansible_facts['distribution'] }} and 
          python version is {{ ansible_facts['python_version'] }}
