---
- name: Demonstrate use of ansible module
  hosts: centos
  vars:
    git_package:
      - git
      - java-17-openjdk
  tasks:
    - name: Check of python is installed in managed nodes
      ansible.builtin.ping:

    - name: Install git and java
      ansible.builtin.dnf:
        name: "{{ git_package }}"
        state: present
