---
- hosts: centos

  tasks:
  - name: Simulate long runnning op, allow to run for 45 sec, fire and forget
    ansible.builtin.shell: sleep 30
    async: 45
    poll: 0 #concurrent task execution
    changed_when: false
  - name: print a statement
    ansible.builtin.debug:
       msg: "WELCOME"
  - name: print second statement
    ansible.builtin.debug:
       msg: "WELCOME AGAIN"