---
- name: Demonstrate use of ansible module
  hosts: centos
  tasks:
    - name: Check of python is installed in managed nodes
      ansible.builtin.ping:

    - name: Install git and java
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - java-17-openjdk
